---
sites:
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    hosts:
      - local.wordpress.dev

  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    hosts:
      - src.wordpress-develop.dev
      - build.wordpress-develop.dev

  # This would create a standard WordPress site in www/example-site available
  # at http;//my-example-site.dev
  # Remember to copy this file to vvv-custom.yml before making changes

  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
  #  hosts:
  #    - my-example-site.dev

  #wordpress-trunk: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-trunk.git
  #multisite: https://github.com/Varying-Vagrant-Vagrants/vvv-multisite.git
  #wordpress-meta-environment: https://github.com/WordPress/meta-environment.git

utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
