---
sites:
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    vm_dir: '/srv/www/wordpress-default-provisioner'
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    vm_dir: '/srv/www/wordpress-develop-provisioner'
  #wordpress-trunk:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-trunk.git
  #  vm_dir: /srv/www/wordpress-trunk-provisioner
  #multisite: https://github.com/Varying-Vagrant-Vagrants/vvv-multisite.git
  #wordpress-meta-environment: https://github.com/WordPress/meta-environment.git

utility-repos:
  unofficial: https://github.com/LoreleiAurora/vvv-utilities-2.git
  unofficial2: https://github.com/LoreleiAurora/vvv-utilities-3.git

utilities:
  official:
    - memcached-admin
  unofficial:
    - test1
    - test2
    - test3
  unofficial2:
    - test4
    - test5
    - test6
